Imported Debian patch 3.7.0-2

diff --git a/debian/ddclient.init b/debian/ddclient.init
--- a/debian/ddclient.init
+++ b/debian/ddclient.init
@@ -4,17 +4,19 @@
 
 ### BEGIN INIT INFO
 # Provides:          ddclient
-# Required-Start:    $local_fs $network
-# Required-Stop:     $local_fs $network
+# Required-Start:    $local_fs $remote_fs $network
+# Required-Stop:     $local_fs $remote_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Update dynamic domain name service entries
 ### END INIT INFO
 
+# Author: Torsten Landschoff <torsten@debian.org>
+
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/ddclient
 NAME="ddclient"
-DESC="dynamic DNS service update utility"
+DAEMON=/usr/sbin/$NAME
+DESC="Dynamic DNS service update utility"
 
 # Don't run if not installed
 test -f $DAEMON || exit 0
@@ -23,35 +25,80 @@ test -f $DAEMON || exit 0
 run_daemon=false
 daemon_interval=300
 
-if [ -f /etc/default/ddclient ]; then
+if [ -r /etc/default/ddclient ]; then
   . /etc/default/ddclient
 fi
 
 OPTIONS="-daemon $daemon_interval -syslog"
-
-set -e
-
 PIDFILE=/var/run/$NAME.pid
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	if [ "$run_daemon" != "true" ]; then
+		return 0
+	fi
+
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --test --start --quiet \
+		--pidfile $PIDFILE --name $NAME --startas $DAEMON \
+		>/dev/null \
+		|| return 1
+
+	start-stop-daemon --start --quiet \
+		--pidfile $PIDFILE --name $NAME --startas $DAEMON \
+		-- $OPTIONS \
+		|| return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	if [ "$run_daemon" != "true" ]; then
+		return 0
+	fi
+
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
+		--pidfile $PIDFILE --name $NAME
+	return "$?"
+}
+
 
 case "$1" in
   start)
-	if [ "$run_daemon" != "true" ]; then
-		exit 0
-	fi
-	echo -n "Starting $DESC: "
-	start-stop-daemon --start --quiet --background \
-		--pidfile $PIDFILE --exec $DAEMON -- $OPTIONS
-	echo "$NAME."
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-	
   stop)
-	if [ "$run_daemon" != "true" ]; then
-		exit 0
-	fi
-	echo -n "Stopping $DESC: "
-	start-stop-daemon --stop --retry 10 --quiet \
-		--pidfile $PIDFILE --oknodo
-	echo "$NAME."
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
 
   status)
@@ -69,42 +116,29 @@ case "$1" in
         fi
         ;;
 	
-  #reload)
-	#
-	#	If the daemon can reload its config files on the fly
-	#	for example by sending it SIGHUP, do it here.
-	#
-	#	If the daemon responds to changes in its config file
-	#	directly anyway, make this a do-nothing entry.
-	#
-	# echo "Reloading $DESC configuration files."
-	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
-	#	/var/run/$NAME.pid --exec $DAEMON
-  #;;
-  
+ 
   restart|force-reload)
-	if [ $run_daemon != "true" ]; then
-		exit 0
-	fi
-	#
-	#	If the "reload" option is implemented, move the "force-reload"
-	#	option to the "reload" entry above. If not, "force-reload" is
-	#	just the same as "restart".
-	#
-	echo -n "Restarting $DESC: "
-	#start-stop-daemon --stop --quiet --pidfile \
-	#	/var/run/$NAME.pid --exec $DAEMON -- $OPTIONS
-	$0 stop >/dev/null
-	$0 start >/dev/null
-	#start-stop-daemon --start --quiet --pidfile \
-	#/var/run/$NAME.pid --exec $DAEMON -- $OPTIONS
-	echo "$NAME."
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
-	
+
   *)
 	N=/etc/init.d/$NAME
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N {start|stop|restart|force-reload}" >&2
+	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
 	exit 1
 	;;
 esac
